version: "3"

services:
  localterra-a:
    image: local:terra
    build:
      context: ../../
      dockerfile: local.Dockerfile
    volumes:
      - ./scripts/setup_chain.sh:/terra/setup.sh
      - $HOME/.terrad-local-a/:/terra/.terrad/
    entrypoint:
      - /terra/setup.sh
    environment:
      - CHAIN_ID=localterra-a
      - VALIDATOR_MONIKER=validator-a
      - VALIDATOR_MNEMONIC=family album bird seek tilt color pill danger message abuse manual tent almost ridge boost blast high comic core quantum spoon coconut oyster remove
      - FAUCET_MNEMONIC=increase bread alpha rigid glide amused approve oblige print asset idea enact lawn proof unfold jeans rabbit audit return chuckle valve rather cactus great
      - RELAYER_MNEMONIC=black frequent sponsor nice claim rally hunt suit parent size stumble expire forest avocado mistake agree trend witness lounge shiver image smoke stool chicken
    ports:
      - 26657:26657
      - 1317:1317
      - 9090:9090
    networks:
      - localterra

  localterra-b:
    image: local:terra
    build:
      context: ../../
      dockerfile: local.Dockerfile
    volumes:
      - ./scripts/setup_chain.sh:/terra/setup.sh
      - $HOME/.terrad-local-b/:/terra/.terrad/
    entrypoint:
      - /terra/setup.sh
    environment:
      - CHAIN_ID=localterra-b
      - VALIDATOR_MONIKER=validator-b
      - VALIDATOR_MNEMONIC=family album bird seek tilt color pill danger message abuse manual tent almost ridge boost blast high comic core quantum spoon coconut oyster remove
      - FAUCET_MNEMONIC=increase bread alpha rigid glide amused approve oblige print asset idea enact lawn proof unfold jeans rabbit audit return chuckle valve rather cactus great
      - RELAYER_MNEMONIC=black frequent sponsor nice claim rally hunt suit parent size stumble expire forest avocado mistake agree trend witness lounge shiver image smoke stool chicken
    ports:
      # Can't use the same ports
      - 36657:26657
      - 31317:1317
      - 39090:9090
    networks:
      - localterra

  hermes:
    image: informalsystems/hermes:1.1.0
    user: root:root
    volumes:
      - ./scripts/setup_hermes.sh:/home/hermes/setup.sh
      - ./config/hermes/config.toml:/root/.hermes/config.toml
    entrypoint:
      - /home/hermes/setup.sh
    environment:
      - CHAIN_A_ID=localterra-a
      - CHAIN_A_MNEMONIC=black frequent sponsor nice claim rally hunt suit parent size stumble expire forest avocado mistake agree trend witness lounge shiver image smoke stool chicken
      - CHAIN_B_ID=localterra-b
      - CHAIN_B_MNEMONIC=black frequent sponsor nice claim rally hunt suit parent size stumble expire forest avocado mistake agree trend witness lounge shiver image smoke stool chicken
    ports:
      - 3000:3000
    depends_on:
      - localterra-a
      - localterra-b
    networks:
      - localterra

networks:
  localterra:
