name: Interchain Tests

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: build_push_image
        uses: docker/build-push-action@v3
        with:
          file: ictest.Dockerfile
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/Genuine-labs/terra-classic-ictest:latest
  test-terra-start:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: Set up Go 1.20
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: checkout code
        uses: actions/checkout@v3

      - run: make ictest-start
        env:
          BRANCH_CI: "latest"

  test-ibc-transfer:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: Set up Go 1.20
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: checkout code
        uses: actions/checkout@v3

      - run: make ictest-ibc
        env:
          BRANCH_CI: "latest"

  test-ibc-hooks:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: Set up Go 1.20
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: checkout code
        uses: actions/checkout@v3

      - run: make ictest-ibc-hooks
        env:
          BRANCH_CI: "latest"
    
  test-ibc-pfm:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: Set up Go 1.20
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: checkout code
        uses: actions/checkout@v3

      - run: make ictest-ibc-pfm
        env:
          BRANCH_CI: "latest"

  test-validator:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: Set up Go 1.20
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: checkout code
        uses: actions/checkout@v3

      - run: make ictest-validator
        env:
          BRANCH_CI: "latest"
